# Generated by Django 4.2 on 2023-11-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='candidate_unique_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voter_unique_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
