# Generated by Django 4.2 on 2023-11-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_userprofile_candidate_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionuser',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth.', null=True),
        ),
    ]
